#version: '3.1'

networks:
  kosa_network:
    driver: bridge

services:
  was1:
    image: sibaru/helloweb:latest
	container_name: was1
    networks:
      - kosa_network

  was2:
    image: sibaru/helloweb:latest
	container_name: was2
    networks:
      - kosa_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kosa_network
    depends_on:
      - was1
      - was2
