name: Our Workflow

on:
  push:
    branches: [ main ]

env:
  repository_name: sibaru/helloweb:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker image build
        run: docker build -t ${{ env.repository_name }} .

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ env.repository_name }}

  deploy:
    needs: build-and-deploy
    name: 서버에 배포 단계
    runs-on: [ self-hosted, label-go2 ]

    steps:
      - name: 운영서버에서 docker hub에 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: docker-compose로 최신 이미지 pull 및 재배포
        run: |
          cd ~/helloWeb
          docker-compose down
          docker-compose pull
          docker-compose up -d
